name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --f Dockerfile --t fibonacci:$(date +%s)
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
           docker push fibonacci:$(date +%s)

