name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}  
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           echo secrets.DOCKER_USER 
           echo secrets.DOCKER_PASSWORD 
           docker build . -f Dockerfile -t fibonacci:$(date +%s)
           docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
           docker push fibonacci:$(date +%s)

