name: Docker Image CI

on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}  
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      TAG: $(date +%s)
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
           docker build . -f Dockerfile -t fibonacci:TAG
       #    docker login -u 028892180 -p OFERmi111
       #    docker push fibonacci:TAG

